### ISSUE TITLE
Discord bot token

### ISSUE THREAD

**Issue by LacticWhale** [EdgyBoi2414/meguiminBot#1]
You committed bot token in config.json file, it will allow anybody use your bot. Please revoke your token and add config.json into .gitignore, so you won't commit it again. 

Maybe [dotenv](https://www.npmjs.com/package/dotenv) would be interesting for you. If you use this packege, don't foget add .env into .gitignore.

**Comment by EdgyBoi2414** [comment]
Thanks for notifying me but that's an old token. Discord reset it as soon as they noticed it had been posted online lol.
